TOPDIR ?= ../..
include $(TOPDIR)/.config

$(FUBOCTRL_SUPPORT)_SRC += services/fuboctrl/fuboctrl.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
